apiVersion: v1
kind: Namespace
metadata:
  name: project2
---
apiVersion: v1
kind: ResourceQuota
metadata:
    name: compute-quota 
    namespace: project2
spec:
    hard:
      requests.cpu: "1"
      requests.memory: 1Gi
      limits.cpu: "2"
      limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: project2
spec:
  hard:
    pods: "4"
    services: "10"
    secrets: "10"
    configmaps: "10"